# Generated by Django 3.0.6 on 2020-05-30 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('input_file_name', models.CharField(max_length=100)),
                ('output_file_name', models.CharField(max_length=100)),
                ('transaction_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'files',
            },
        ),
        migrations.CreateModel(
            name='financial_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=50)),
                ('field_value', models.IntegerField()),
                ('year', models.IntegerField()),
                ('transaction_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'financial_data',
            },
        ),
    ]
