# Generated by Django 3.0.6 on 2020-05-30 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financial_data',
            name='file',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='files',
            name='input_file_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='files',
            name='output_file_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='financial_data',
            name='field_name',
            field=models.CharField(max_length=500),
        ),
    ]
