# Generated by Django 3.0.6 on 2020-05-30 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0004_auto_20200530_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='transaction_time',
        ),
        migrations.RemoveField(
            model_name='financial_data',
            name='transaction_time',
        ),
    ]
