# Generated by Django 3.0.6 on 2020-05-30 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0005_auto_20200530_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='transaction_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financial_data',
            name='transaction_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
